Repository ImpulsoGov/farolcovid, pull requests merged in 2020-10, with the labels that each got.

#209 Update main.py
  src/pages/main.py
Labels: frontend

#210 Minor fix: Rt plot text & bounds
  src/configs/config.yaml
  src/pages/main.py
  src/plots.py
Labels: frontend

#215 Add GTM for Google Analytics reports
  src/pages/main.py
Labels: analysis

#218 Update CNES + GTM
  src/configs/config.yaml
  src/pages/main.py
Labels: backend
