Repository ImpulsoGov/farolcovid, pull requests merged in 2020-12, with the labels that each got.

#220 OndaCovid adjustments
  src/pages/data_analysis.py
Labels: backend, model enhancement

#211 Update main.py
  src/pages/main.py
Labels: documentation

#227 Added memory use improvements.
  src/pages/data_analysis.py
  src/pages/onda_covid.py
Labels: backend
