Repository ImpulsoGov/farolcovid, pull requests merged in 2020-07, with the labels that each got.

#161 Test session with user key
  src/pages/main.py
  src/session.py
Labels: backend, bug

#164 ⚠️ Major Fixes on SimulaCovid
  src/model/simulator.py
  src/pages/main.py
  src/pages/simulacovid.py
  src/utils.py
Labels: backend, bug

#168 Add new reopening URLs
  src/configs/config.yaml
Labels: backend

#173 Added support to Google Analytics
  requirements.txt
  src/farolcovid.py
  src/pages/main.py
Labels: backend

#179 Saude Em Ordem Version 2
  src/farolcovid.py
  src/pages/main.py
  src/pages/saude_em_ordem.py
  src/resources/hide-iframes.html
  src/resources/horizontalize-radio.html
  src/resources/redo-button.html
  src/style.css
  src/utils.py
Labels: frontend
